<?php
define('DUEL', 'Duel');
define('CREATE', 'Create');
define('LEADERBOARD', 'Leaderboard');
define('MY_ACCOUNT', 'My account');
define('LOGOUT', 'Log out');
define('USERNAME', 'Username');
define('EMAIL', 'Email Address');
define('PASSWORD', 'Password');
define('NEW_PASSWORD', 'New password');
define('CHANGE_PASSWORD', 'Change Password');
define('EMPTY_PASSWORD', 'EMPTY_PASSWORD CHANGE');
define('SUCCESSFUL_REGISTRATION', 'Successful registration, log in now');
define('BY_CREATING_AN_ACCOUNT', 'By creating an account you agree to our');
define('TERMS_AND_PRIVACY', 'Privacy Policy');
define('ALREADY_HAVE_AN_ACCOUNT', 'Already have an account?');
define('SUBMIT', 'Submit');
define('ERASE_ACCOUNT', 'eraseAccount CHANGE');
define('ERASE_USER_IMAGE', 'eraseUserImage CHANGE');
define('CANCEL', 'cancel CHANGE');
define('SAVE', 'save CHANGE');
define('SIGN_UP', 'Sign Up');
define('USERNAME_EMPTY', 'Username can\'t be empty');
define('EMAIL_INCORRECT', 'mailIncorrect CHANGE');
define('EMAIL_EMPTY', 'mailEmpty CHANGE');
define('REGISTRATION_FAILED', 'registrationFailed CHANGE');
define('EMAIL_ALREADY_USED', 'emailAlreadyUsed CHANGE');
define('USERNAME_ALREADY_USED', 'Username already used');
define('LOG_IN', 'Log In');
define('NO_ACCOUNT', 'Don\'t have an account?');
define('CREATE_ONE', 'Create one here.');
define('FORGOT_PASSWORD', 'Reset Password.');
define('SUCCESSFUL_LOG_IN', 'Successful login');
define('CLICK_HERE_TO_CONNECT', 'Click here to log in. ');
define('OPPONENT_USERNAME', 'Opponent username');
define('EMAIL_ADDRESS_OR_PASSWORD_INCORRECT', 'email address or password incorrect');

